/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Nomor11;

/**
 *
 * @author Asus
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PlainText01 = new javax.swing.JTextField();
        CipherText01 = new javax.swing.JTextField();
        tombolCaesarCipher = new javax.swing.JButton();
        tombolCaesarPlain = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Key01 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        PlainText02 = new javax.swing.JTextField();
        tombolVigenereEncript = new javax.swing.JButton();
        Hapus02 = new javax.swing.JButton();
        tombolVigenereDescript = new javax.swing.JButton();
        Key02 = new javax.swing.JTextField();
        CipherText02 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 600));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 40));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 18)); // NOI18N
        jLabel1.setText("Caesar Cipher");
        jPanel3.add(jLabel1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Plain Text ");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setText("Cipher Text");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jPanel4.add(PlainText01, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 230, -1));
        jPanel4.add(CipherText01, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 230, -1));

        tombolCaesarCipher.setText("Encript to Cipher");
        tombolCaesarCipher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCaesarCipherActionPerformed(evt);
            }
        });
        jPanel4.add(tombolCaesarCipher, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        tombolCaesarPlain.setText("Deckript to Plain");
        tombolCaesarPlain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCaesarPlainActionPerformed(evt);
            }
        });
        jPanel4.add(tombolCaesarPlain, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        delete.setText("Clear");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel4.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 90, -1));

        jLabel4.setText("Key");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));
        jPanel4.add(Key01, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 230, -1));

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText(" Vigenere Cipher");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel5)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Plain Text");

        tombolVigenereEncript.setText("Encript to Cipher");
        tombolVigenereEncript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolVigenereEncriptActionPerformed(evt);
            }
        });

        Hapus02.setText("Clear");
        Hapus02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hapus02ActionPerformed(evt);
            }
        });

        tombolVigenereDescript.setText("Deckript to Plain");
        tombolVigenereDescript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolVigenereDescriptActionPerformed(evt);
            }
        });

        Key02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Key02ActionPerformed(evt);
            }
        });

        CipherText02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CipherText02ActionPerformed(evt);
            }
        });

        jLabel6.setText("Key");

        jLabel7.setText("Cipher Text");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Key02, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(PlainText02)
                            .addComponent(CipherText02))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombolVigenereEncript)
                            .addComponent(tombolVigenereDescript)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(Hapus02, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(PlainText02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolVigenereEncript))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Key02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CipherText02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolVigenereDescript)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35)
                .addComponent(Hapus02)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolCaesarCipherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCaesarCipherActionPerformed
        String plainText = PlainText01.getText().toLowerCase();
        int key = Integer.parseInt(Key01.getText());
        String encript = CaesarEncript(plainText, key);
        CipherText01.setText(encript.toUpperCase());

    }//GEN-LAST:event_tombolCaesarCipherActionPerformed

    private void tombolCaesarPlainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCaesarPlainActionPerformed
        String encript = CipherText01.getText().toLowerCase();
        int key = Integer.parseInt(Key01.getText());
        String plainText = CaesarDecript(encript, key);
        PlainText01.setText(plainText.toUpperCase());
    }//GEN-LAST:event_tombolCaesarPlainActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        CipherText01.setText("");
        PlainText01.setText("");
        Key01.setText("");
    }//GEN-LAST:event_deleteActionPerformed

    private void Key02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Key02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Key02ActionPerformed

    private void CipherText02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CipherText02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CipherText02ActionPerformed

    private void tombolVigenereEncriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolVigenereEncriptActionPerformed
        String plainText = PlainText02.getText().toLowerCase();
        String key = Key02.getText().toLowerCase();
        String encript = VigenereEncript(plainText, key);
        CipherText02.setText(encript.toUpperCase());
    }//GEN-LAST:event_tombolVigenereEncriptActionPerformed

    private void tombolVigenereDescriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolVigenereDescriptActionPerformed
        String encript = CipherText02.getText().toLowerCase();
        String key = Key02.getText().toLowerCase();
        String plainText = VigenereteDectript(encript, key);
        PlainText02.setText(plainText.toUpperCase());
    }//GEN-LAST:event_tombolVigenereDescriptActionPerformed

    private void Hapus02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hapus02ActionPerformed
        PlainText02.setText("");
        Key02.setText("");
        CipherText02.setText("");
    }//GEN-LAST:event_Hapus02ActionPerformed
    private static String CaesarEncript(String text, int shift) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < text.length(); i++) {
            int p = text.charAt(i) - 97;//plainText
            int e = (p + shift) % 26;//hasilEncript
            char huruf = (char) (e + 97);//mengarah ke huruf sesuai angka
            sb.append(huruf);
        }
        return sb.toString();
    }

    private static String CaesarDecript(String text, int shift) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < text.length(); i++) {
            int e = text.charAt(i) - 97;
            int p = (e - shift) % 26;
            if (p < 0) {
                p += 26;
            }
            char huruf = (char) (p + 97);//kembali ke angka ascii
            sb.append(huruf);
        }
        return sb.toString();
    }

    private static String VigenereEncript(String text, String shift) {
        StringBuffer sb = new StringBuffer();
        int panjang = text.length();
        for (int i = 0; i < panjang; i++) {
            int j = i % shift.length();
            int k = (int) shift.charAt(j) - 97;
            int p = text.charAt(i) - 97;
            int e = (p + k) % 26;
            char huruf = (char) (e + 97);
            sb.append(huruf);

        }
        return sb.toString();
    }

    private static String VigenereteDectript(String text, String shift) {
        StringBuffer sb = new StringBuffer();
        int panjang = text.length();
        for (int i = 0; i < panjang; i++) {
            int j = i % shift.length();// j hasil modulo i, biar tidak melebihi key
            int k = (int) shift.charAt(j) - 97;
            int p = text.charAt(i) - 97;
            int e = (p - k) % 26;
            if (e < 0) {
                e += 26;

            }
            char huruf = (char) (e + 97);
            sb.append(huruf);
        }
        return sb.toString();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CipherText01;
    private javax.swing.JTextField CipherText02;
    private javax.swing.JButton Hapus02;
    private javax.swing.JTextField Key01;
    private javax.swing.JTextField Key02;
    private javax.swing.JTextField PlainText01;
    private javax.swing.JTextField PlainText02;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton tombolCaesarCipher;
    private javax.swing.JButton tombolCaesarPlain;
    private javax.swing.JButton tombolVigenereDescript;
    private javax.swing.JButton tombolVigenereEncript;
    // End of variables declaration//GEN-END:variables
}
